description = "Generates a Git commit message based on staged changes."
prompt = """
 generate a Conventional Commit message based on the following git diff:

```diff
!{git diff --staged}
```

  use the following for types of changes: 
  - for style changes use  STYLE: 
  - for bug fixes use  BUG: 
  - for new features use  FEATURE: 
  - for docs use  DOCS: 
"""
